---
# Usage:
# docker-compose build
# docker-compose down; docker-compose up --build --detach
# docker-compose down; docker rmi -f fshare_tool_app; docker rmi $(docker images --filter "dangling=true" -q --no-trunc) -f; docker-compose up --build --detach

version: '3.8'

services:
  app:
    image: 'hoanghiepitvnn/fshare_tool'
    restart: always
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
      args:
        BUNDLER_VERSION: $BUNDLER_VERSION
        WORKSPACE: $WORKSPACE
        RAILS_PORT: $RAILS_PORT
    ports:
      - 7777:$RAILS_PORT
    environment:
      VLC_RC_HOST: $VLC_RC_HOST
      VLC_RC_PORT: $VLC_RC_PORT
      FSHARE_USER_EMAIL: $FSHARE_USER_EMAIL
      FSHARE_PASSWORD: $FSHARE_PASSWORD
      FSHARE_APP_KEY: $FSHARE_APP_KEY
      FSHARE_USER_AGENT: $FSHARE_USER_AGENT
    volumes:
      - app_dbs:/var/workspace/db/sqlite_dbs
volumes:
  app_dbs:
    driver: local
